#! /bin/bash
read -p "Introduce el texto que quieres añadir al fichero: " text
echo "El texto actual del archivo se borrara, escribe o para sobreescribir / A to append"

echo "El texto actual del archivo se borrará: o-overrite/a-append" input
read -n1 input
if [ $input = 'o' ] ; then
	echo "$text" > carlos

else
	echo "$text" >> carlos
fi
echo ""
echo "Correctly written"
